-- LET Reviewer PH — 500 Question Bank
-- Run in Supabase SQL Editor

INSERT INTO questions (subject, topic, difficulty, question_text, choices, correct_answer, explanation, exam_type) VALUES

-- CHILD AND ADOLESCENT DEVELOPMENT (1-40)
('Professional Education','Child and Adolescent Development','medium','According to Piaget, which stage is characterized by abstract thinking and hypothetical reasoning?','[{"key":"A","text":"Sensorimotor"},{"key":"B","text":"Preoperational"},{"key":"C","text":"Concrete Operational"},{"key":"D","text":"Formal Operational"}]','D','The Formal Operational stage (12+ years) is marked by abstract thought, hypothetical reasoning, and logical deduction.','both'),

('Professional Education','Child and Adolescent Development','easy','Vygotsky''s Zone of Proximal Development (ZPD) refers to:','[{"key":"A","text":"Tasks a child can do independently"},{"key":"B","text":"Tasks too difficult even with help"},{"key":"C","text":"The gap between what a child can do alone and with guidance"},{"key":"D","text":"The child''s comfort zone in learning"}]','C','ZPD is the distance between actual development (independent) and potential development (with skilled guidance).','both'),

('Professional Education','Child and Adolescent Development','medium','Erik Erikson''s stage for adolescents (12–18 years) is:','[{"key":"A","text":"Industry vs. Inferiority"},{"key":"B","text":"Identity vs. Role Confusion"},{"key":"C","text":"Intimacy vs. Isolation"},{"key":"D","text":"Initiative vs. Guilt"}]','B','Erikson''s fifth stage involves adolescents forming a personal identity; failure leads to role confusion.','both'),

('Professional Education','Child and Adolescent Development','medium','Which Piagetian concept refers to a child''s inability to see things from another person''s perspective?','[{"key":"A","text":"Conservation"},{"key":"B","text":"Centration"},{"key":"C","text":"Egocentrism"},{"key":"D","text":"Animism"}]','C','Egocentrism in the preoperational stage means the child cannot take another''s viewpoint.','both'),

('Professional Education','Child and Adolescent Development','easy','Object permanence — understanding that objects exist even when out of sight — develops in Piaget''s:','[{"key":"A","text":"Sensorimotor stage"},{"key":"B","text":"Preoperational stage"},{"key":"C","text":"Concrete Operational stage"},{"key":"D","text":"Formal Operational stage"}]','A','Object permanence emerges around 8–12 months during the Sensorimotor stage.','both'),

('Professional Education','Child and Adolescent Development','medium','Scaffolding, as used in Vygotsky''s theory, means:','[{"key":"A","text":"Punishing incorrect responses"},{"key":"B","text":"Providing temporary support to help a learner accomplish a task"},{"key":"C","text":"Letting children learn entirely on their own"},{"key":"D","text":"Grouping students by ability"}]','B','Scaffolding is temporary assistance given by a more capable person, gradually withdrawn as the learner gains competence.','both'),

('Professional Education','Child and Adolescent Development','hard','Kohlberg''s postconventional level of moral development includes which stage?','[{"key":"A","text":"Punishment and obedience"},{"key":"B","text":"Instrumental purpose"},{"key":"C","text":"Social contract and universal ethical principles"},{"key":"D","text":"Good boy/good girl orientation"}]','C','Postconventional morality involves abstract principles of justice and human rights beyond social rules.','both'),

('Professional Education','Child and Adolescent Development','easy','Which theorist proposed the concept of multiple intelligences?','[{"key":"A","text":"Jean Piaget"},{"key":"B","text":"Howard Gardner"},{"key":"C","text":"Lev Vygotsky"},{"key":"D","text":"Erik Erikson"}]','B','Howard Gardner proposed 8 intelligences: linguistic, logical-mathematical, spatial, musical, bodily-kinesthetic, interpersonal, intrapersonal, and naturalist.','both'),

('Professional Education','Child and Adolescent Development','medium','Bronfenbrenner''s microsystem refers to:','[{"key":"A","text":"The broader cultural context"},{"key":"B","text":"Interactions between two settings the child is in"},{"key":"C","text":"The immediate environment (family, school, peers)"},{"key":"D","text":"Historical and time-based influences"}]','C','The microsystem is the immediate setting where the child directly interacts, such as home and school.','both'),

('Professional Education','Child and Adolescent Development','medium','In Piaget''s theory, assimilation means:','[{"key":"A","text":"Changing existing schemas to fit new information"},{"key":"B","text":"Integrating new information into existing schemas"},{"key":"C","text":"The balance between assimilation and accommodation"},{"key":"D","text":"Creating entirely new schemas"}]','B','Assimilation is incorporating new experiences into existing mental frameworks without changing them.','both'),

('Professional Education','Child and Adolescent Development','easy','Erikson''s stage for school-age children (6–12) is:','[{"key":"A","text":"Initiative vs. Guilt"},{"key":"B","text":"Trust vs. Mistrust"},{"key":"C","text":"Industry vs. Inferiority"},{"key":"D","text":"Autonomy vs. Shame"}]','C','School-age children develop competence through learning; failure leads to feelings of inferiority.','both'),

('Professional Education','Child and Adolescent Development','medium','A child who believes the moon follows them as they walk is demonstrating:','[{"key":"A","text":"Animism"},{"key":"B","text":"Egocentrism"},{"key":"C","text":"Conservation"},{"key":"D","text":"Centration"}]','B','Egocentrism causes the child to believe the world revolves around them, including the moon "following" them.','both'),

('Professional Education','Child and Adolescent Development','medium','Conservation, the understanding that quantity remains the same despite changes in shape, develops in:','[{"key":"A","text":"Sensorimotor stage"},{"key":"B","text":"Preoperational stage"},{"key":"C","text":"Concrete Operational stage"},{"key":"D","text":"Formal Operational stage"}]','C','Concrete Operational children (7–11) can understand conservation of number, mass, and volume.','both'),

('Professional Education','Child and Adolescent Development','easy','Which stage of Erikson involves the crisis of "Trust vs. Mistrust"?','[{"key":"A","text":"Toddlerhood"},{"key":"B","text":"Infancy (0–1 year)"},{"key":"C","text":"Preschool"},{"key":"D","text":"School age"}]','B','The first stage of Erikson''s theory occurs in infancy; consistent caregiving builds trust.','both'),

('Professional Education','Child and Adolescent Development','hard','Kohlberg''s Stage 3 (Good Boy/Good Girl orientation) belongs to which level?','[{"key":"A","text":"Preconventional"},{"key":"B","text":"Conventional"},{"key":"C","text":"Postconventional"},{"key":"D","text":"Pre-moral"}]','B','Stage 3 is part of the Conventional level where moral decisions are based on social approval.','both'),

('Professional Education','Child and Adolescent Development','medium','A teacher who adapts instruction to a student''s ZPD is applying:','[{"key":"A","text":"Behaviorism"},{"key":"B","text":"Maturation theory"},{"key":"C","text":"Vygotsky''s sociocultural theory"},{"key":"D","text":"Freud''s psychoanalysis"}]','C','Instructing within the ZPD with scaffolding is a direct application of Vygotsky''s theory.','both'),

('Professional Education','Child and Adolescent Development','easy','Gardner''s intelligence related to understanding others is called:','[{"key":"A","text":"Intrapersonal"},{"key":"B","text":"Interpersonal"},{"key":"C","text":"Linguistic"},{"key":"D","text":"Spatial"}]','B','Interpersonal intelligence involves understanding and interacting effectively with others.','both'),

('Professional Education','Child and Adolescent Development','medium','Which of Bronfenbrenner''s systems involves interactions between two environments a child participates in?','[{"key":"A","text":"Microsystem"},{"key":"B","text":"Mesosystem"},{"key":"C","text":"Exosystem"},{"key":"D","text":"Macrosystem"}]','B','The mesosystem includes the connections between two microsystems, such as home-school relationships.','both'),

('Professional Education','Child and Adolescent Development','hard','Accommodation in Piaget''s theory occurs when:','[{"key":"A","text":"A child fits new information into an old schema"},{"key":"B","text":"A child modifies an existing schema to fit new information"},{"key":"C","text":"Equilibrium is achieved"},{"key":"D","text":"A child ignores conflicting information"}]','B','Accommodation involves changing existing schemas when new information cannot be assimilated.','both'),

('Professional Education','Child and Adolescent Development','medium','A child in the preoperational stage who believes clouds feel sad is demonstrating:','[{"key":"A","text":"Egocentrism"},{"key":"B","text":"Centration"},{"key":"C","text":"Animism"},{"key":"D","text":"Irreversibility"}]','C','Animism is the belief that inanimate objects have life and feelings.','both'),

('Professional Education','Child and Adolescent Development','easy','Maslow''s hierarchy places which need at the top?','[{"key":"A","text":"Safety needs"},{"key":"B","text":"Esteem needs"},{"key":"C","text":"Self-actualization"},{"key":"D","text":"Physiological needs"}]','C','Self-actualization — reaching one''s full potential — is at the pinnacle of Maslow''s hierarchy.','both'),

('Professional Education','Child and Adolescent Development','medium','Which Erikson stage involves the crisis experienced by young adults (19–40)?','[{"key":"A","text":"Identity vs. Role Confusion"},{"key":"B","text":"Intimacy vs. Isolation"},{"key":"C","text":"Generativity vs. Stagnation"},{"key":"D","text":"Ego Integrity vs. Despair"}]','B','Young adults face the challenge of forming intimate relationships; failure leads to isolation.','both'),

('Professional Education','Child and Adolescent Development','medium','The "private speech" children use while solving problems is associated with:','[{"key":"A","text":"Piaget''s egocentrism"},{"key":"B","text":"Vygotsky''s inner speech development"},{"key":"C","text":"Erikson''s initiative stage"},{"key":"D","text":"Kohlberg''s moral reasoning"}]','B','Vygotsky viewed private speech as a self-regulatory tool that eventually becomes internalized thought.','both'),

('Professional Education','Child and Adolescent Development','hard','In Bronfenbrenner''s model, the chronosystem refers to:','[{"key":"A","text":"The cultural values of society"},{"key":"B","text":"Settings the child is not directly involved in"},{"key":"C","text":"Changes over time including historical events"},{"key":"D","text":"Direct interactions with family"}]','C','The chronosystem encompasses the dimension of time — changes in the child and environment over time.','both'),

('Professional Education','Child and Adolescent Development','easy','Which stage of Piaget involves learning through senses and motor actions (birth to 2 years)?','[{"key":"A","text":"Preoperational"},{"key":"B","text":"Concrete Operational"},{"key":"C","text":"Formal Operational"},{"key":"D","text":"Sensorimotor"}]','D','The Sensorimotor stage involves learning through direct sensory experience and motor actions.','both'),

('Professional Education','Child and Adolescent Development','medium','A student who studies hard to win a scholarship (external reward) is motivated by:','[{"key":"A","text":"Intrinsic motivation"},{"key":"B","text":"Self-actualization"},{"key":"C","text":"Extrinsic motivation"},{"key":"D","text":"Cognitive dissonance"}]','C','Extrinsic motivation is driven by external rewards such as money, grades, or recognition.','both'),

('Professional Education','Child and Adolescent Development','medium','The concept of "nature vs. nurture" in development refers to:','[{"key":"A","text":"Teachers vs. parents"},{"key":"B","text":"Genetics vs. environment"},{"key":"C","text":"School vs. home"},{"key":"D","text":"Intelligence vs. emotion"}]','B','The nature-nurture debate concerns the relative contributions of genetic inheritance and environmental experience.','both'),

('Professional Education','Child and Adolescent Development','hard','According to Kohlberg, most adults operate at which level of moral development?','[{"key":"A","text":"Preconventional"},{"key":"B","text":"Postconventional"},{"key":"C","text":"Conventional"},{"key":"D","text":"Transitional"}]','C','Research shows most adults reason at the conventional level, following social rules and laws.','both'),

('Professional Education','Child and Adolescent Development','easy','Gardner''s intelligence involving sensitivity to music and rhythm is:','[{"key":"A","text":"Spatial"},{"key":"B","text":"Bodily-kinesthetic"},{"key":"C","text":"Linguistic"},{"key":"D","text":"Musical"}]','D','Musical intelligence involves skill in rhythm, pitch, melody, and musical pattern recognition.','both'),

('Professional Education','Child and Adolescent Development','medium','Which theorist emphasized the role of social interaction and culture in cognitive development?','[{"key":"A","text":"Jean Piaget"},{"key":"B","text":"B.F. Skinner"},{"key":"C","text":"Lev Vygotsky"},{"key":"D","text":"Sigmund Freud"}]','C','Vygotsky''s sociocultural theory emphasizes that learning is a social process mediated by culture and language.','both'),

('Professional Education','Child and Adolescent Development','medium','Equilibration in Piaget''s theory is:','[{"key":"A","text":"The process of forgetting old information"},{"key":"B","text":"The drive to balance assimilation and accommodation"},{"key":"C","text":"A type of memory consolidation"},{"key":"D","text":"The transition from one stage to another"}]','B','Equilibration is the self-regulatory mechanism that drives cognitive development by balancing assimilation and accommodation.','both'),

('Professional Education','Child and Adolescent Development','easy','Which of the following describes a "scheme" in Piaget''s theory?','[{"key":"A","text":"A classroom seating plan"},{"key":"B","text":"A mental framework for organizing information"},{"key":"C","text":"A type of behavioral reinforcement"},{"key":"D","text":"A student''s learning style"}]','B','Schemas (schemes) are cognitive structures used to organize and interpret information about the world.','both'),

('Professional Education','Child and Adolescent Development','medium','Erikson''s stage of "Initiative vs. Guilt" occurs during:','[{"key":"A","text":"Infancy"},{"key":"B","text":"School age"},{"key":"C","text":"Preschool (3–6 years)"},{"key":"D","text":"Adolescence"}]','C','Preschoolers develop initiative through play; excessive criticism leads to guilt.','both'),

('Professional Education','Child and Adolescent Development','hard','A child who cannot understand that rolling a ball of clay into a snake doesn''t change its mass lacks:','[{"key":"A","text":"Object permanence"},{"key":"B","text":"Conservation"},{"key":"C","text":"Reversibility"},{"key":"D","text":"Seriation"}]','B','Conservation is the understanding that properties like mass, volume, and number remain constant despite physical changes.','both'),

('Professional Education','Child and Adolescent Development','medium','Bowlby''s attachment theory states that:','[{"key":"A","text":"Children learn through observation"},{"key":"B","text":"Early emotional bonds with caregivers shape future relationships"},{"key":"C","text":"Intelligence is genetically determined"},{"key":"D","text":"Play is the primary mode of learning"}]','B','Bowlby proposed that secure early attachment to caregivers provides a foundation for healthy emotional development.','both'),

('Professional Education','Child and Adolescent Development','easy','According to Maslow, which needs must be met first before higher needs can be pursued?','[{"key":"A","text":"Esteem needs"},{"key":"B","text":"Love and belonging"},{"key":"C","text":"Physiological needs"},{"key":"D","text":"Safety needs"}]','C','Physiological needs (food, water, shelter) are at the base of Maslow''s hierarchy and must be satisfied first.','both'),

('Professional Education','Child and Adolescent Development','medium','A teenager questioning "Who am I?" is experiencing Erikson''s:','[{"key":"A","text":"Industry vs. Inferiority"},{"key":"B","text":"Identity vs. Role Confusion"},{"key":"C","text":"Autonomy vs. Shame"},{"key":"D","text":"Intimacy vs. Isolation"}]','B','The identity crisis of adolescence involves exploring values, beliefs, and goals to form a coherent sense of self.','both'),

('Professional Education','Child and Adolescent Development','medium','Which Piaget stage involves logical thinking but only with concrete objects?','[{"key":"A","text":"Sensorimotor"},{"key":"B","text":"Preoperational"},{"key":"C","text":"Concrete Operational"},{"key":"D","text":"Formal Operational"}]','C','Concrete operational children (7–11) can think logically about tangible, concrete objects but not abstract concepts.','both'),

('Professional Education','Child and Adolescent Development','hard','Gardner''s naturalist intelligence involves:','[{"key":"A","text":"Understanding musical patterns"},{"key":"B","text":"Recognizing and classifying natural objects"},{"key":"C","text":"Logical reasoning"},{"key":"D","text":"Bodily movement and coordination"}]','B','Naturalist intelligence is the ability to recognize and categorize natural objects like plants and animals.','both'),

('Professional Education','Child and Adolescent Development','medium','Bronfenbrenner''s macrosystem refers to:','[{"key":"A","text":"The immediate family setting"},{"key":"B","text":"Cultural values, laws, and customs of society"},{"key":"C","text":"Connections between home and school"},{"key":"D","text":"Settings the child doesn''t directly experience"}]','B','The macrosystem encompasses the overarching cultural, social, and political context that influences all other systems.','both'),

('Professional Education','Child and Adolescent Development','easy','A child who begins to use symbols (words, images) to represent objects is in Piaget''s:','[{"key":"A","text":"Sensorimotor stage"},{"key":"B","text":"Preoperational stage"},{"key":"C","text":"Concrete Operational stage"},{"key":"D","text":"Formal Operational stage"}]','B','Symbolic function — using words and images to represent objects — emerges in the Preoperational stage (2–7 years).','both'),

-- FACILITATING LEARNING (41-80)
('Professional Education','Facilitating Learning','easy','Pavlov''s classical conditioning involves learning through:','[{"key":"A","text":"Reward and punishment"},{"key":"B","text":"Association between a neutral stimulus and a natural response"},{"key":"C","text":"Observation and imitation"},{"key":"D","text":"Trial and error"}]','B','Classical conditioning pairs a neutral stimulus with an unconditioned stimulus to elicit a conditioned response.','both'),

('Professional Education','Facilitating Learning','medium','Skinner''s operant conditioning is based on:','[{"key":"A","text":"Association of stimuli"},{"key":"B","text":"Consequences (reinforcement and punishment) shaping behavior"},{"key":"C","text":"Innate biological drives"},{"key":"D","text":"Social observation"}]','B','Operant conditioning holds that behaviors followed by positive consequences are strengthened; those followed by negative consequences are weakened.','both'),

('Professional Education','Facilitating Learning','easy','Positive reinforcement means:','[{"key":"A","text":"Adding a pleasant stimulus to increase a behavior"},{"key":"B","text":"Removing an unpleasant stimulus to increase a behavior"},{"key":"C","text":"Adding an unpleasant stimulus to decrease a behavior"},{"key":"D","text":"Removing a pleasant stimulus to decrease a behavior"}]','A','Positive reinforcement adds a desirable stimulus after a behavior to increase its frequency.','both'),

('Professional Education','Facilitating Learning','medium','Bandura''s social learning theory emphasizes:','[{"key":"A","text":"Conditioning through rewards"},{"key":"B","text":"Learning through observation and modeling"},{"key":"C","text":"Innate cognitive structures"},{"key":"D","text":"Unconscious drives"}]','B','Bandura proposed that people learn by observing others; behavior, environment, and cognition interact (reciprocal determinism).','both'),

('Professional Education','Facilitating Learning','medium','Self-efficacy, according to Bandura, refers to:','[{"key":"A","text":"One''s actual ability to perform a task"},{"key":"B","text":"One''s belief in their ability to succeed at a task"},{"key":"C","text":"Motivation from external rewards"},{"key":"D","text":"Intelligence quotient"}]','B','Self-efficacy is the belief in one''s capability to execute behaviors necessary to achieve specific goals.','both'),

('Professional Education','Facilitating Learning','easy','Bloom''s lowest level of cognitive taxonomy is:','[{"key":"A","text":"Application"},{"key":"B","text":"Analysis"},{"key":"C","text":"Knowledge/Remembering"},{"key":"D","text":"Synthesis"}]','C','The original Bloom''s taxonomy starts with Knowledge; the revised version starts with Remembering.','both'),

('Professional Education','Facilitating Learning','medium','Which level of Bloom''s taxonomy requires students to judge the value of information?','[{"key":"A","text":"Comprehension"},{"key":"B","text":"Application"},{"key":"C","text":"Synthesis"},{"key":"D","text":"Evaluation"}]','D','Evaluation (the highest level) involves making judgments about the value of ideas or materials.','both'),

('Professional Education','Facilitating Learning','medium','Ausubel''s meaningful learning theory states that new learning must be:','[{"key":"A","text":"Based solely on rote memorization"},{"key":"B","text":"Connected to existing knowledge in the learner''s mind"},{"key":"C","text":"Discovered independently by the learner"},{"key":"D","text":"Taught through direct instruction only"}]','B','Ausubel believed new knowledge must be anchored to prior knowledge for meaningful (not rote) learning to occur.','both'),

('Professional Education','Facilitating Learning','medium','Advance organizers, used before teaching new material, serve to:','[{"key":"A","text":"Assess prior knowledge through testing"},{"key":"B","text":"Provide a framework connecting new and existing knowledge"},{"key":"C","text":"Motivate students through rewards"},{"key":"D","text":"Summarize material after a lesson"}]','B','Advance organizers are introductory materials presented at a higher level of abstraction that bridge new and prior learning.','both'),

('Professional Education','Facilitating Learning','medium','Jerome Bruner''s discovery learning involves:','[{"key":"A","text":"Teacher presenting complete, organized content"},{"key":"B","text":"Students constructing knowledge through exploration"},{"key":"C","text":"Rote repetition of facts"},{"key":"D","text":"Behavioral conditioning"}]','B','Bruner advocated for active exploration and discovery as the primary means of constructing knowledge.','both'),

('Professional Education','Facilitating Learning','easy','Metacognition refers to:','[{"key":"A","text":"Learning through memorization"},{"key":"B","text":"Thinking about one''s own thinking and learning processes"},{"key":"C","text":"Imitating a teacher''s behavior"},{"key":"D","text":"Using multiple senses to learn"}]','B','Metacognition is the awareness and regulation of one''s own cognitive processes — "thinking about thinking."','both'),

('Professional Education','Facilitating Learning','hard','Transfer of learning is BEST facilitated when:','[{"key":"A","text":"Students memorize information without understanding"},{"key":"B","text":"There is high similarity between the learning and application contexts"},{"key":"C","text":"Learning is purely theoretical"},{"key":"D","text":"Students compete with each other"}]','B','Transfer is maximized when the conditions of practice are similar to the conditions of application.','both'),

('Professional Education','Facilitating Learning','medium','Constructivism as a learning theory holds that:','[{"key":"A","text":"Knowledge is passively received from teachers"},{"key":"B","text":"Learners actively construct meaning from experiences"},{"key":"C","text":"Learning is primarily a product of reinforcement"},{"key":"D","text":"Intelligence is fixed at birth"}]','B','Constructivism, associated with Piaget and Vygotsky, holds that learners build knowledge through active experience.','both'),

('Professional Education','Facilitating Learning','medium','Which learning theory is associated with "tabula rasa" (blank slate)?','[{"key":"A","text":"Constructivism"},{"key":"B","text":"Humanism"},{"key":"C","text":"Behaviorism"},{"key":"D","text":"Cognitivism"}]','C','Behaviorism views the learner as a blank slate shaped entirely by environmental stimuli and reinforcement.','both'),

('Professional Education','Facilitating Learning','easy','Negative reinforcement involves:','[{"key":"A","text":"Adding a punishment to stop a behavior"},{"key":"B","text":"Removing an aversive stimulus to increase a behavior"},{"key":"C","text":"Ignoring a behavior to reduce it"},{"key":"D","text":"Adding praise to encourage a behavior"}]','B','Negative reinforcement removes something unpleasant when a desired behavior occurs, increasing that behavior.','both'),

('Professional Education','Facilitating Learning','medium','The revised Bloom''s taxonomy (Anderson & Krathwohl) highest level is:','[{"key":"A","text":"Synthesis"},{"key":"B","text":"Evaluation"},{"key":"C","text":"Creating"},{"key":"D","text":"Analyzing"}]','C','The revised taxonomy changed "Synthesis" to "Creating" and moved it to the highest level above Evaluating.','both'),

('Professional Education','Facilitating Learning','medium','Cooperative learning differs from traditional group work because it requires:','[{"key":"A","text":"Individual competition"},{"key":"B","text":"Positive interdependence and individual accountability"},{"key":"C","text":"Teacher-led instruction"},{"key":"D","text":"Homogeneous grouping"}]','B','Cooperative learning requires both positive interdependence (success depends on the group) and individual accountability.','both'),

('Professional Education','Facilitating Learning','hard','Thorndike''s Law of Effect states that:','[{"key":"A","text":"Practice makes perfect"},{"key":"B","text":"Behaviors followed by satisfying consequences are strengthened"},{"key":"C","text":"Organisms learn by observation"},{"key":"D","text":"Repetition alone is sufficient for learning"}]','B','The Law of Effect is the precursor to operant conditioning — behaviors with positive outcomes are repeated; those with negative outcomes are avoided.','both'),

('Professional Education','Facilitating Learning','medium','Intrinsic motivation in learning is best described as:','[{"key":"A","text":"Studying to earn high grades"},{"key":"B","text":"Learning driven by curiosity, interest, and personal satisfaction"},{"key":"C","text":"Performing to please the teacher"},{"key":"D","text":"Motivation from scholarship rewards"}]','B','Intrinsic motivation comes from within the learner — interest, curiosity, and the joy of learning itself.','both'),

('Professional Education','Facilitating Learning','medium','In Gagné''s conditions of learning, the first internal condition required is:','[{"key":"A","text":"Attention"},{"key":"B","text":"Recall of prior learning"},{"key":"C","text":"Motivation and alertness"},{"key":"D","text":"Feedback"}]','C','Gagné''s nine events of instruction begin with gaining the learner''s attention and motivation.','both'),

('Professional Education','Facilitating Learning','easy','Which learning style (VAK) prefers to learn by doing and hands-on activities?','[{"key":"A","text":"Visual"},{"key":"B","text":"Auditory"},{"key":"C","text":"Kinesthetic"},{"key":"D","text":"Linguistic"}]','C','Kinesthetic learners learn best through physical experience, movement, and hands-on activities.','both'),

('Professional Education','Facilitating Learning','medium','Mastery learning (Bloom) holds that:','[{"key":"A","text":"Only gifted students can master all content"},{"key":"B","text":"All students can achieve mastery if given adequate time and instruction"},{"key":"C","text":"Speed of learning determines mastery"},{"key":"D","text":"Content should never be simplified"}]','B','Bloom''s mastery learning proposes that virtually all students can master content if instruction is appropriate and time is sufficient.','both'),

('Professional Education','Facilitating Learning','medium','Problem-based learning (PBL) is characterized by:','[{"key":"A","text":"Teacher presenting solutions directly"},{"key":"B","text":"Students solving complex real-world problems as the starting point"},{"key":"C","text":"Rote memorization of formulas"},{"key":"D","text":"Individual seatwork only"}]','B','PBL uses ill-structured real-world problems as the vehicle for learning, promoting critical thinking and collaboration.','both'),

('Professional Education','Facilitating Learning','hard','The information processing model compares human memory to a computer. Working memory is analogous to:','[{"key":"A","text":"Hard drive storage"},{"key":"B","text":"RAM (active processing space)"},{"key":"C","text":"CPU speed"},{"key":"D","text":"Input devices"}]','B','Working memory (short-term memory) holds information for active processing, similar to computer RAM.','both'),

('Professional Education','Facilitating Learning','medium','Differentiated instruction means:','[{"key":"A","text":"Teaching the same lesson to all students"},{"key":"B","text":"Adjusting content, process, and product based on student needs"},{"key":"C","text":"Grouping only by ability"},{"key":"D","text":"Reducing curriculum content"}]','B','Differentiated instruction tailors teaching strategies, content, and assessments to individual student readiness, interests, and learning profiles.','both'),

('Professional Education','Facilitating Learning','easy','Extinction in operant conditioning occurs when:','[{"key":"A","text":"A behavior is punished repeatedly"},{"key":"B","text":"A reinforced behavior decreases because reinforcement is withheld"},{"key":"C","text":"A new behavior replaces an old one"},{"key":"D","text":"A stimulus is repeatedly presented"}]','B','Extinction is the weakening of a conditioned response when reinforcement is no longer provided.','both'),

('Professional Education','Facilitating Learning','medium','Brain-based learning advocates for:','[{"key":"A","text":"Strict rote memorization"},{"key":"B","text":"Instruction aligned with how the brain naturally learns"},{"key":"C","text":"Punishment-based discipline"},{"key":"D","text":"Single-modality instruction"}]','B','Brain-based learning applies neuroscience research — emotion, patterns, and meaning enhance learning and memory.','both'),

('Professional Education','Facilitating Learning','medium','The jigsaw cooperative learning strategy involves:','[{"key":"A","text":"Each student mastering one piece and teaching it to the group"},{"key":"B","text":"All students doing the same task simultaneously"},{"key":"C","text":"Teacher dividing students by ability"},{"key":"D","text":"Individual competition for rewards"}]','A','In jigsaw, each student becomes an "expert" on one portion of material and teaches it to their home group.','both'),

('Professional Education','Facilitating Learning','hard','Which theorist proposed that intelligence is not fixed and can be developed through effort?','[{"key":"A","text":"Charles Spearman"},{"key":"B","text":"Alfred Binet"},{"key":"C","text":"Carol Dweck (Growth Mindset)"},{"key":"D","text":"Lewis Terman"}]','C','Carol Dweck''s growth mindset theory holds that abilities can be developed through dedication and hard work.','both'),

('Professional Education','Facilitating Learning','medium','Inquiry-based learning is most aligned with which theory?','[{"key":"A","text":"Behaviorism"},{"key":"B","text":"Constructivism"},{"key":"C","text":"Humanism"},{"key":"D","text":"Essentialism"}]','B','Inquiry-based learning, where students explore and construct understanding, aligns with constructivist principles.','both'),

('Professional Education','Facilitating Learning','easy','Which of the following is an example of positive reinforcement in the classroom?','[{"key":"A","text":"Taking away recess for misbehavior"},{"key":"B","text":"Giving a sticker to a student who completes homework"},{"key":"C","text":"Ignoring a student who acts out"},{"key":"D","text":"Removing homework when students behave"}]','B','Giving a sticker (pleasant stimulus) after completing homework (desired behavior) is positive reinforcement.','both'),

('Professional Education','Facilitating Learning','medium','The concept of "flow" in learning, described by Csikszentmihalyi, refers to:','[{"key":"A","text":"Using water tables in science"},{"key":"B","text":"A state of deep, effortless engagement in an appropriately challenging task"},{"key":"C","text":"Group discussion techniques"},{"key":"D","text":"Transitions between lessons"}]','B','Flow is the optimal experience of full immersion and enjoyment in an activity that is challenging yet achievable.','both'),

('Professional Education','Facilitating Learning','hard','Universal Design for Learning (UDL) provides:','[{"key":"A","text":"One standard method of instruction for all"},{"key":"B","text":"Multiple means of representation, engagement, and expression"},{"key":"C","text":"Special education only for disabled students"},{"key":"D","text":"Standardized tests for all learners"}]','B','UDL proactively designs flexible learning materials and activities to accommodate all learners'' variability.','both'),

('Professional Education','Facilitating Learning','medium','Which learning theory emphasizes the whole is greater than the sum of its parts?','[{"key":"A","text":"Behaviorism"},{"key":"B","text":"Cognitivism"},{"key":"C","text":"Gestalt psychology"},{"key":"D","text":"Humanism"}]','C','Gestalt psychology focuses on how the mind organizes sensory information into meaningful wholes and patterns.','both'),

('Professional Education','Facilitating Learning','easy','Modeling as a teaching strategy is based on:','[{"key":"A","text":"Pavlov''s classical conditioning"},{"key":"B","text":"Bandura''s observational learning"},{"key":"C","text":"Skinner''s operant conditioning"},{"key":"D","text":"Piaget''s constructivism"}]','B','Modeling involves demonstrating a behavior for students to observe and imitate, rooted in Bandura''s social learning theory.','both'),

('Professional Education','Facilitating Learning','medium','A student who studies because they genuinely enjoy the subject demonstrates:','[{"key":"A","text":"Extrinsic motivation"},{"key":"B","text":"Instrumental motivation"},{"key":"C","text":"Intrinsic motivation"},{"key":"D","text":"Achievement motivation"}]','C','Intrinsic motivation arises from internal factors like genuine interest and enjoyment of the activity itself.','both'),

('Professional Education','Facilitating Learning','medium','Chunking in information processing refers to:','[{"key":"A","text":"Breaking a lesson into daily parts"},{"key":"B","text":"Grouping individual pieces of information into meaningful units"},{"key":"C","text":"Separating students by ability"},{"key":"D","text":"Using flash cards for memorization"}]','B','Chunking increases working memory capacity by grouping information into larger, meaningful units (e.g., remembering a phone number).','both'),

('Professional Education','Facilitating Learning','hard','The "spacing effect" in learning research shows that:','[{"key":"A","text":"Massed practice is more effective than distributed practice"},{"key":"B","text":"Distributed practice over time leads to better long-term retention"},{"key":"C","text":"Short intensive study sessions are always best"},{"key":"D","text":"Frequency of review has no effect on retention"}]','B','The spacing effect demonstrates that studying material over spaced intervals produces superior long-term memory compared to cramming.','both'),

('Professional Education','Facilitating Learning','medium','Think-Pair-Share is a strategy that promotes:','[{"key":"A","text":"Individual silent work"},{"key":"B","text":"Active processing, peer discussion, and class sharing"},{"key":"C","text":"Teacher-centered lecturing"},{"key":"D","text":"Written examinations"}]','B','Think-Pair-Share engages all learners by having them reflect, discuss with a partner, then share with the class.','both'),

('Professional Education','Facilitating Learning','easy','Which theorist is associated with the "hierarchy of needs" applied to motivation in education?','[{"key":"A","text":"B.F. Skinner"},{"key":"B","text":"Abraham Maslow"},{"key":"C","text":"Carl Rogers"},{"key":"D","text":"Albert Bandura"}]','B','Maslow''s hierarchy of needs (physiological → safety → love → esteem → self-actualization) is widely applied to classroom motivation.','both'),

-- ASSESSMENT OF LEARNING (81-115)
('Professional Education','Assessment of Learning','easy','Formative assessment is primarily used to:','[{"key":"A","text":"Assign final grades"},{"key":"B","text":"Monitor student learning and provide feedback during instruction"},{"key":"C","text":"Rank students at the end of a term"},{"key":"D","text":"Select students for advanced programs"}]','B','Formative assessment is ongoing assessment during learning to guide instruction and provide feedback.','both'),

('Professional Education','Assessment of Learning','easy','Summative assessment is used to:','[{"key":"A","text":"Diagnose learning difficulties before instruction"},{"key":"B","text":"Provide feedback during the learning process"},{"key":"C","text":"Evaluate student achievement at the end of a unit or course"},{"key":"D","text":"Group students for instruction"}]','C','Summative assessment evaluates what students have learned at the end of an instructional period (e.g., final exams, unit tests).','both'),

('Professional Education','Assessment of Learning','medium','Validity in assessment means:','[{"key":"A","text":"The assessment produces consistent results"},{"key":"B","text":"The assessment measures what it is supposed to measure"},{"key":"C","text":"The assessment is easy to administer"},{"key":"D","text":"All students score similarly"}]','B','Validity is the degree to which an assessment accurately measures the intended knowledge, skills, or abilities.','both'),

('Professional Education','Assessment of Learning','medium','Reliability in assessment refers to:','[{"key":"A","text":"The assessment measures the right content"},{"key":"B","text":"The consistency of assessment results across repeated administration"},{"key":"C","text":"The fairness of the scoring procedure"},{"key":"D","text":"The difficulty level of test items"}]','B','Reliability means the assessment produces stable, consistent results when administered under similar conditions.','both'),

('Professional Education','Assessment of Learning','hard','A test that is reliable but not valid is:','[{"key":"A","text":"Acceptable for high-stakes decisions"},{"key":"B","text":"Consistently measuring the wrong thing"},{"key":"C","text":"Both accurate and consistent"},{"key":"D","text":"Always suitable for classroom use"}]','B','A reliable test consistently produces the same results, but if those results don''t reflect the intended construct, it is not valid.','both'),

('Professional Education','Assessment of Learning','medium','The item difficulty index (p) of 0.90 indicates:','[{"key":"A","text":"The item is very difficult"},{"key":"B","text":"The item is very easy"},{"key":"C","text":"The item has good discrimination"},{"key":"D","text":"The item is invalid"}]','B','An item difficulty index close to 1.0 means most students answered correctly — the item is easy.','both'),

('Professional Education','Assessment of Learning','medium','Item discrimination index tells us:','[{"key":"A","text":"How difficult an item is"},{"key":"B","text":"How well an item distinguishes high from low performers"},{"key":"C","text":"The number of students who answered correctly"},{"key":"D","text":"The time needed to answer an item"}]','B','The discrimination index measures how effectively an item separates students who know the material from those who do not.','both'),

('Professional Education','Assessment of Learning','easy','A portfolio assessment collects:','[{"key":"A","text":"Only final exam results"},{"key":"B","text":"Evidence of student learning over time"},{"key":"C","text":"Standardized test scores only"},{"key":"D","text":"Teacher observations only"}]','B','Portfolios systematically collect student work samples over time to demonstrate growth and achievement.','both'),

('Professional Education','Assessment of Learning','medium','Authentic assessment requires students to:','[{"key":"A","text":"Answer multiple choice questions"},{"key":"B","text":"Demonstrate knowledge through real-world tasks"},{"key":"C","text":"Memorize and recite content"},{"key":"D","text":"Take standardized tests"}]','B','Authentic assessment involves tasks that reflect real-world application of knowledge and skills.','both'),

('Professional Education','Assessment of Learning','medium','A rubric provides:','[{"key":"A","text":"A list of student names"},{"key":"B","text":"Clear criteria and performance levels for evaluating student work"},{"key":"C","text":"Raw scores for standardized tests"},{"key":"D","text":"Attendance records"}]','B','Rubrics describe the criteria and levels of quality used to evaluate student performance consistently.','both'),

('Professional Education','Assessment of Learning','medium','Norm-referenced assessment compares:','[{"key":"A","text":"Student performance against a fixed standard"},{"key":"B","text":"Student performance against others in the norm group"},{"key":"C","text":"Student performance against their own past results"},{"key":"D","text":"Different schools'' curricula"}]','B','Norm-referenced tests rank students relative to a norming group (e.g., national average); used for percentile ranks.','both'),

('Professional Education','Assessment of Learning','medium','Criterion-referenced assessment compares student performance to:','[{"key":"A","text":"Other students in the class"},{"key":"B","text":"National norms"},{"key":"C","text":"A predetermined standard or learning objective"},{"key":"D","text":"Teacher expectations"}]','C','Criterion-referenced tests measure whether students have achieved specific learning outcomes, not how they compare to others.','both'),

('Professional Education','Assessment of Learning','easy','Diagnostic assessment is conducted:','[{"key":"A","text":"At the end of a unit"},{"key":"B","text":"Before instruction to identify student strengths and weaknesses"},{"key":"C","text":"During instruction as feedback"},{"key":"D","text":"To assign final grades"}]','B','Diagnostic assessment is given before instruction to understand what students already know and identify gaps.','both'),

('Professional Education','Assessment of Learning','hard','The Table of Specifications (TOS) in test construction ensures:','[{"key":"A","text":"All questions are of equal difficulty"},{"key":"B","text":"Test items are aligned to objectives and proportionally distributed across topics"},{"key":"C","text":"Tests are easy enough for all students"},{"key":"D","text":"Questions are arranged randomly"}]','B','The TOS maps test items to instructional objectives by topic and cognitive level to ensure content validity.','both'),

('Professional Education','Assessment of Learning','medium','Which measure of central tendency is most affected by extreme scores?','[{"key":"A","text":"Mode"},{"key":"B","text":"Median"},{"key":"C","text":"Mean"},{"key":"D","text":"Range"}]','C','The mean (average) is sensitive to extreme values (outliers), unlike the median or mode.','both'),

('Professional Education','Assessment of Learning','medium','A student scores at the 75th percentile. This means:','[{"key":"A","text":"They answered 75% of items correctly"},{"key":"B","text":"They scored higher than 75% of the norm group"},{"key":"C","text":"They failed the exam"},{"key":"D","text":"They scored 75 points out of 100"}]','B','A percentile rank of 75 means the student scored equal to or higher than 75% of the comparison group.','both'),

('Professional Education','Assessment of Learning','hard','An analytic rubric differs from a holistic rubric in that it:','[{"key":"A","text":"Gives one overall score for the entire performance"},{"key":"B","text":"Evaluates each criterion separately with its own score"},{"key":"C","text":"Only works for objective tests"},{"key":"D","text":"Does not use performance levels"}]','B','Analytic rubrics score each dimension/criterion independently, providing detailed feedback; holistic rubrics give a single overall score.','both'),

('Professional Education','Assessment of Learning','medium','Self-assessment in the classroom develops:','[{"key":"A","text":"Dependence on the teacher for evaluation"},{"key":"B","text":"Metacognitive awareness and learner responsibility"},{"key":"C","text":"Competition among students"},{"key":"D","text":"Standardized performance"}]','B','Self-assessment develops students'' ability to reflect on and judge their own work, fostering metacognition and autonomy.','both'),

('Professional Education','Assessment of Learning','medium','Performance-based assessment is most suitable for measuring:','[{"key":"A","text":"Factual recall of information"},{"key":"B","text":"Applied skills and complex thinking"},{"key":"C","text":"Speed of reading"},{"key":"D","text":"Attendance records"}]','B','Performance-based assessment evaluates how well students apply knowledge and skills in real or simulated tasks.','both'),

('Professional Education','Assessment of Learning','easy','In a normal distribution, what percentage of scores falls within one standard deviation of the mean?','[{"key":"A","text":"50%"},{"key":"B","text":"68%"},{"key":"C","text":"95%"},{"key":"D","text":"99%"}]','B','In a normal distribution, approximately 68% of data falls within ±1 standard deviation of the mean.','both'),

('Professional Education','Assessment of Learning','medium','Higher-order thinking skills (HOTS) in assessment require students to:','[{"key":"A","text":"Recall and memorize facts"},{"key":"B","text":"Analyze, evaluate, and create"},{"key":"C","text":"Copy examples from the board"},{"key":"D","text":"Complete drill and practice"}]','B','HOTS involves Bloom''s upper levels — analysis, evaluation, and creation — requiring deeper cognitive processing.','both'),

('Professional Education','Assessment of Learning','medium','The standard deviation in a test measures:','[{"key":"A","text":"The highest score achieved"},{"key":"B","text":"The spread or variability of scores around the mean"},{"key":"C","text":"The average score of the class"},{"key":"D","text":"The number of students who passed"}]','B','Standard deviation indicates how much scores vary from the mean; a high SD means scores are widely spread.','both'),

('Professional Education','Assessment of Learning','hard','When a test consistently measures something other than what it was designed to measure, it has:','[{"key":"A","text":"High reliability but low validity"},{"key":"B","text":"High validity but low reliability"},{"key":"C","text":"Both high validity and reliability"},{"key":"D","text":"Neither validity nor reliability"}]','A','A test can be reliable (consistent) yet invalid (measuring the wrong construct) — reliability does not guarantee validity.','both'),

('Professional Education','Assessment of Learning','medium','The best type of assessment for measuring practical laboratory skills is:','[{"key":"A","text":"Multiple choice test"},{"key":"B","text":"True-false test"},{"key":"C","text":"Performance-based assessment"},{"key":"D","text":"Essay test"}]','C','Laboratory skills are best assessed through direct observation of performance — a hallmark of performance-based assessment.','both'),

('Professional Education','Assessment of Learning','medium','Peer assessment in the classroom:','[{"key":"A","text":"Replaces the teacher''s grading responsibility"},{"key":"B","text":"Develops evaluative skills and promotes collaborative learning"},{"key":"C","text":"Is unreliable and should be avoided"},{"key":"D","text":"Only works for older students"}]','B','Peer assessment enhances critical thinking, develops evaluation skills, and encourages students to learn from each other.','both'),

-- CURRICULUM DEVELOPMENT (116-145)
('Professional Education','Curriculum Development','medium','Tyler''s Rationale (1949) begins curriculum development with:','[{"key":"A","text":"Selecting learning experiences"},{"key":"B","text":"Determining educational purposes"},{"key":"C","text":"Organizing learning experiences"},{"key":"D","text":"Evaluating outcomes"}]','B','Tyler''s four-step model starts with identifying educational purposes/objectives, then selecting experiences, organizing, and evaluating.','both'),

('Professional Education','Curriculum Development','medium','The hidden curriculum refers to:','[{"key":"A","text":"Secret government education plans"},{"key":"B","text":"Unwritten, informal lessons students learn in school"},{"key":"C","text":"Advanced curriculum for gifted students"},{"key":"D","text":"Online curriculum resources"}]','B','The hidden curriculum encompasses implicit messages, values, and norms students learn through the school culture and environment.','both'),

('Professional Education','Curriculum Development','medium','The null curriculum refers to:','[{"key":"A","text":"Topics teachers choose to skip"},{"key":"B","text":"What is NOT taught but students notice is absent"},{"key":"C","text":"The official government curriculum"},{"key":"D","text":"After-school programs"}]','B','Eisner''s null curriculum refers to what schools choose not to teach — the absence itself sends a message about value.','both'),

('Professional Education','Curriculum Development','easy','The K-12 curriculum in the Philippines was implemented under:','[{"key":"A","text":"Republic Act 7836"},{"key":"B","text":"Republic Act 10533"},{"key":"C","text":"Republic Act 9293"},{"key":"D","text":"Republic Act 7722"}]','B','RA 10533 (Enhanced Basic Education Act of 2013) mandated the K-12 curriculum adding Grades 11 and 12.','both'),

('Professional Education','Curriculum Development','medium','Spiral progression in the K-12 curriculum means:','[{"key":"A","text":"Students skip grades based on performance"},{"key":"B","text":"Topics are revisited at increasing levels of complexity across grades"},{"key":"C","text":"Curriculum only covers Math and Science"},{"key":"D","text":"Teachers rotate subjects yearly"}]','B','Spiral progression revisits key concepts at progressively deeper levels as learners advance, building on prior knowledge.','both'),

('Professional Education','Curriculum Development','medium','Backward design (Wiggins & McTighe) begins with:','[{"key":"A","text":"Selecting teaching activities"},{"key":"B","text":"Identifying desired results/outcomes first"},{"key":"C","text":"Writing lesson plans"},{"key":"D","text":"Choosing textbooks"}]','B','Backward design starts with the end in mind — desired learning outcomes — then determines acceptable evidence and plans instruction.','both'),

('Professional Education','Curriculum Development','hard','Taba''s model of curriculum development is described as:','[{"key":"A","text":"Top-down, administrative-driven"},{"key":"B","text":"Grassroots, teacher-driven starting with specific diagnoses"},{"key":"C","text":"Student-centered without teacher input"},{"key":"D","text":"Exclusively theory-based"}]','B','Taba advocated for a bottom-up approach starting with teachers diagnosing needs, then developing units inductively.','both'),

('Professional Education','Curriculum Development','medium','Curriculum alignment means:','[{"key":"A","text":"All teachers using the same textbook"},{"key":"B","text":"Objectives, instruction, and assessment are all consistent with each other"},{"key":"C","text":"Students achieving equal scores"},{"key":"D","text":"Schools following international standards only"}]','B','Curriculum alignment ensures that what is taught (instruction) and how it is measured (assessment) match the intended learning objectives.','both'),

('Professional Education','Curriculum Development','medium','Outcome-based education (OBE) focuses on:','[{"key":"A","text":"Content delivery as the primary goal"},{"key":"B","text":"Clearly defined learning outcomes that students must demonstrate"},{"key":"C","text":"Standardized textbook use"},{"key":"D","text":"Teacher qualifications"}]','B','OBE organizes the entire educational system around clearly defined outcomes — what students should know and be able to do.','both'),

('Professional Education','Curriculum Development','easy','Which type of curriculum is officially documented in government-mandated guides?','[{"key":"A","text":"Hidden curriculum"},{"key":"B","text":"Null curriculum"},{"key":"C","text":"Explicit/Official curriculum"},{"key":"D","text":"Experienced curriculum"}]','C','The explicit or official curriculum is the formally documented, government-approved content and standards.','both'),

('Professional Education','Curriculum Development','medium','Scope in curriculum refers to:','[{"key":"A","text":"The order in which content is arranged"},{"key":"B","text":"The breadth and depth of content covered"},{"key":"C","text":"The connections between subjects"},{"key":"D","text":"The continuity of topics across grades"}]','B','Scope refers to the range of content, skills, and experiences included in the curriculum at a given level.','both'),

('Professional Education','Curriculum Development','medium','Sequence in curriculum development means:','[{"key":"A","text":"Covering all topics simultaneously"},{"key":"B","text":"The order in which content is organized from simple to complex"},{"key":"C","text":"Repeating content each year without change"},{"key":"D","text":"Using alphabetical order for topics"}]','B','Sequence refers to the logical, progressive order of content — usually from simple to complex or known to unknown.','both'),

('Professional Education','Curriculum Development','hard','An integrated curriculum:','[{"key":"A","text":"Teaches each subject in complete isolation"},{"key":"B","text":"Connects two or more subjects around a common theme"},{"key":"C","text":"Covers only core subjects"},{"key":"D","text":"Is used only in special education"}]','B','Integrated curriculum breaks down subject barriers by organizing content around themes, problems, or concepts across disciplines.','both'),

('Professional Education','Curriculum Development','medium','The experiences curriculum refers to:','[{"key":"A","text":"What is officially written in the curriculum guide"},{"key":"B","text":"What students actually learn and experience in school"},{"key":"C","text":"Extra-curricular activities"},{"key":"D","text":"The curriculum before K-12"}]','B','The experienced (or received) curriculum is what students actually encounter and internalize — which may differ from the official plan.','both'),

('Professional Education','Curriculum Development','medium','Subject-centered curriculum design focuses on:','[{"key":"A","text":"The interests and needs of learners"},{"key":"B","text":"Organized academic disciplines and content"},{"key":"C","text":"Social problems and current issues"},{"key":"D","text":"Individual learning plans"}]','B','Subject-centered design organizes curriculum around disciplines (Math, Science, English) prioritizing content mastery.','both'),

-- TEACHING PROFESSION (146-170)
('Professional Education','The Teaching Profession','easy','Republic Act 7836 is known as the:','[{"key":"A","text":"Magna Carta for Public School Teachers"},{"key":"B","text":"Philippine Teachers Professionalization Act of 1994"},{"key":"C","text":"K-12 Basic Education Act"},{"key":"D","text":"CHED Act"}]','B','RA 7836 professionalizes teaching in the Philippines and created the Licensure Examination for Teachers (LET).','both'),

('Professional Education','The Teaching Profession','medium','Under the Code of Ethics for Professional Teachers, the teacher''s primary obligation is to:','[{"key":"A","text":"The school administration"},{"key":"B","text":"The student and their best interest"},{"key":"C","text":"Parents only"},{"key":"D","text":"The government"}]','B','Article IV of the Code states that a teacher''s first concern is the learner''s growth and development.','both'),

('Professional Education','The Teaching Profession','medium','The Philippine Professional Standards for Teachers (PPST) replaced the:','[{"key":"A","text":"RA 7836"},{"key":"B","text":"NCBTS (National Competency-Based Teacher Standards)"},{"key":"C","text":"K-12 curriculum"},{"key":"D","text":"Code of Ethics"}]','B','DepEd Order No. 42 (2017) replaced the NCBTS with the PPST, outlining standards for teacher quality.','both'),

('Professional Education','The Teaching Profession','medium','The Magna Carta for Public School Teachers (RA 4670) grants teachers:','[{"key":"A","text":"Authority to dismiss students"},{"key":"B","text":"Rights including academic freedom, security of tenure, and professional benefits"},{"key":"C","text":"Power over school budget"},{"key":"D","text":"Exemption from professional examinations"}]','B','RA 4670 protects public school teachers'' rights to tenure, fair compensation, academic freedom, and professional development.','both'),

('Professional Education','The Teaching Profession','easy','A teacher demonstrates professionalism by:','[{"key":"A","text":"Sharing confidential student information with other parents"},{"key":"B","text":"Continuously updating subject knowledge and teaching skills"},{"key":"C","text":"Giving passing grades to all students regardless of performance"},{"key":"D","text":"Prioritizing personal interests over student welfare"}]','B','Professionalism includes continuous learning, ethical conduct, and placing student welfare above personal convenience.','both'),

('Professional Education','The Teaching Profession','medium','Under the Code of Ethics, a teacher should NOT:','[{"key":"A","text":"Use auxiliary materials to enrich lessons"},{"key":"B","text":"Make deductions from student grades as punishment for behavior"},{"key":"C","text":"Involve parents in student progress"},{"key":"D","text":"Attend professional development activities"}]','B','The Code prohibits using grades as punishment; grades should reflect academic performance only.','both'),

('Professional Education','The Teaching Profession','hard','Action research in the teaching profession is intended to:','[{"key":"A","text":"Publish academic papers in journals"},{"key":"B","text":"Solve specific classroom or school problems through systematic inquiry"},{"key":"C","text":"Evaluate teachers for promotion only"},{"key":"D","text":"Replace formal teaching methods"}]','B','Action research enables teachers to study their own practice, identify problems, implement solutions, and improve student outcomes.','both'),

('Professional Education','The Teaching Profession','medium','A teacher who reflects on their practice and continuously improves is called a:','[{"key":"A","text":"Traditional teacher"},{"key":"B","text":"Reflective practitioner"},{"key":"C","text":"Subject matter expert"},{"key":"D","text":"Academic researcher"}]','B','A reflective practitioner examines their own teaching, identifies areas for improvement, and adjusts their practice accordingly.','both'),

('Professional Education','The Teaching Profession','medium','Section 7 of Article XIV of the 1987 Philippine Constitution states that:','[{"key":"A","text":"Education is optional for all Filipinos"},{"key":"B","text":"The state shall assign the highest budgetary priority to education"},{"key":"C","text":"All teachers must be licensed by age 25"},{"key":"D","text":"English is the only language of instruction"}]','B','The Philippine Constitution mandates that education receives the highest budgetary priority to foster patriotism, competence, and values.','both'),

('Professional Education','The Teaching Profession','easy','The Professional Regulation Commission (PRC) administers the LET through the:','[{"key":"A","text":"CHED"},{"key":"B","text":"Board for Professional Teachers (BPT)"},{"key":"C","text":"DepEd"},{"key":"D","text":"TESDA"}]','B','The Board for Professional Teachers (BPT) under PRC administers and oversees the LET and teacher licensure.','both'),

('Professional Education','The Teaching Profession','medium','A teacher who accepts gifts from parents in exchange for higher grades violates:','[{"key":"A","text":"The K-12 curriculum"},{"key":"B","text":"The Code of Ethics for Professional Teachers"},{"key":"C","text":"RA 10533"},{"key":"D","text":"The school''s grading policy only"}]','B','The Code of Ethics prohibits teachers from accepting gifts that create obligations affecting their professional judgment.','both'),

('Professional Education','The Teaching Profession','hard','The PPST has how many domains?','[{"key":"A","text":"5"},{"key":"B","text":"6"},{"key":"C","text":"7"},{"key":"D","text":"8"}]','C','The Philippine Professional Standards for Teachers (PPST) has 7 domains covering content knowledge, pedagogy, assessment, and professional responsibilities.','both'),

('Professional Education','The Teaching Profession','medium','Republic Act 9293 amends RA 7836 by:','[{"key":"A","text":"Removing the LET requirement"},{"key":"B","text":"Allowing graduates of non-education courses to teach after completing 18 professional education units and passing the LET"},{"key":"C","text":"Creating TESDA"},{"key":"D","text":"Establishing the K-12 curriculum"}]','B','RA 9293 opened teaching to non-education graduates who complete 18 units of professional education subjects and pass the LET.','both'),

-- PRINCIPLES OF TEACHING (171-200)
('Professional Education','Principles of Teaching','medium','The direct instruction model is characterized by:','[{"key":"A","text":"Student-led exploration without teacher guidance"},{"key":"B","text":"Explicit teacher modeling, guided practice, and independent practice"},{"key":"C","text":"Purely student discovery"},{"key":"D","text":"No feedback to students"}]','B','Direct instruction involves clear learning objectives, teacher modeling, guided practice with feedback, and independent application.','both'),

('Professional Education','Principles of Teaching','easy','A well-written learning objective should be:','[{"key":"A","text":"Vague to allow student interpretation"},{"key":"B","text":"Specific, measurable, and student-centered"},{"key":"C","text":"Based only on teacher preferences"},{"key":"D","text":"Focused exclusively on content coverage"}]','B','Good objectives (SMART) are specific, measurable, achievable, relevant, and time-bound — stated in terms of student performance.','both'),

('Professional Education','Principles of Teaching','medium','The inductive teaching method involves:','[{"key":"A","text":"Presenting a rule first, then examples"},{"key":"B","text":"Moving from specific examples to a general principle"},{"key":"C","text":"Using only textbook content"},{"key":"D","text":"Teacher telling students all answers"}]','B','Inductive teaching builds from specific observations to general conclusions, encouraging critical thinking.','both'),

('Professional Education','Principles of Teaching','medium','The deductive teaching method involves:','[{"key":"A","text":"Moving from specific to general"},{"key":"B","text":"Starting with a general principle and applying it to specific cases"},{"key":"C","text":"Students discovering rules on their own"},{"key":"D","text":"Purely experiential learning"}]','B','Deductive teaching presents the rule or principle first, then demonstrates it through examples and application.','both'),

('Professional Education','Principles of Teaching','easy','Set induction (motivation) at the beginning of a lesson is designed to:','[{"key":"A","text":"Assess students'' prior knowledge only"},{"key":"B","text":"Capture attention and connect to prior learning"},{"key":"C","text":"Give homework instructions"},{"key":"D","text":"Summarize the previous lesson"}]','B','Set induction activates prior knowledge, arouses curiosity, and establishes purpose at the start of instruction.','both'),

('Professional Education','Principles of Teaching','medium','Wait time in questioning refers to:','[{"key":"A","text":"Time students wait to enter the classroom"},{"key":"B","text":"The pause after a question before calling on a student"},{"key":"C","text":"Detention time for misbehavior"},{"key":"D","text":"Time between tests"}]','B','Research shows that increasing wait time (3–5 seconds) after questions improves the quality and quantity of student responses.','both'),

('Professional Education','Principles of Teaching','medium','Probing questions in teaching are used to:','[{"key":"A","text":"Trick students into wrong answers"},{"key":"B","text":"Encourage deeper thinking and elaboration on responses"},{"key":"C","text":"Test only factual recall"},{"key":"D","text":"Speed up the lesson"}]','B','Probing questions follow up on student answers to encourage clarification, justification, and deeper reasoning.','both'),

('Professional Education','Principles of Teaching','medium','The project method in teaching is best used for:','[{"key":"A","text":"Quick factual drills"},{"key":"B","text":"Long-term, complex tasks integrating multiple skills"},{"key":"C","text":"Daily warm-up activities"},{"key":"D","text":"Individual silent reading"}]','B','The project method engages students in extended, meaningful tasks that require planning, research, and application.','both'),

('Professional Education','Principles of Teaching','easy','Role-playing as a teaching strategy is most effective for:','[{"key":"A","text":"Mathematics computation"},{"key":"B","text":"Developing empathy and understanding social situations"},{"key":"C","text":"Memorizing vocabulary"},{"key":"D","text":"Conducting laboratory experiments"}]','B','Role-playing allows students to experience perspectives different from their own, building social understanding and empathy.','both'),

('Professional Education','Principles of Teaching','medium','Classroom management primarily aims to:','[{"key":"A","text":"Punish misbehaving students"},{"key":"B","text":"Create a safe, orderly environment conducive to learning"},{"key":"C","text":"Keep students quiet at all times"},{"key":"D","text":"Fill class time with activities"}]','B','Effective classroom management establishes routines and norms that maximize learning time and student engagement.','both'),

('Professional Education','Principles of Teaching','medium','Which seating arrangement best promotes whole-class discussion?','[{"key":"A","text":"Traditional rows facing the board"},{"key":"B","text":"U-shape or circle arrangement"},{"key":"C","text":"Individual pods spread across the room"},{"key":"D","text":"Students seated by height"}]','B','U-shaped or circular seating allows eye contact between all participants, facilitating discussion and interaction.','both'),

('Professional Education','Principles of Teaching','hard','The "flipped classroom" model involves:','[{"key":"A","text":"Students teaching each other without teacher guidance"},{"key":"B","text":"Students learning content at home and using class time for practice/discussion"},{"key":"C","text":"Teaching outdoors instead of in the classroom"},{"key":"D","text":"Reversing the grading scale"}]','B','In flipped classrooms, students access instructional content (videos, readings) at home, freeing class time for active, collaborative work.','both');
