-- LET Reviewer PH — Question Bank Batch 3 (Questions 401-500)

INSERT INTO questions (subject, topic, difficulty, question_text, choices, correct_answer, explanation, exam_type) VALUES

-- FILIPINO (401-450)
('General Education','Filipino - Gramatika','easy','Alin ang tamang gamit ng pang-uri?','[{"key":"A","text":"Mabilis tumakbo si Pedro."},{"key":"B","text":"Si Pedro ay mabilis na mananakbo."},{"key":"C","text":"Tumakbo nang mabilis si Pedro."},{"key":"D","text":"Mabilis si Pedro na tumakbo."}]','C','Ang pang-uri ay nagpapaliwanag sa katangian ng pangngalan o panghalip. Sa "Tumakbo nang mabilis si Pedro," ginagamit ang pang-uri na "mabilis" bilang pang-abay upang ilarawan ang pandiwa.','both'),

('General Education','Filipino - Gramatika','medium','Ang salitang "umalis" ay isang halimbawa ng pandiwang:','[{"key":"A","text":"Palipat"},{"key":"B","text":"Katawanin"},{"key":"C","text":"Di-palipat (intransitive)"},{"key":"D","text":"Balintiyak"}]','C','Ang di-palipat na pandiwa ay walang tuwirang layon. Ang "umalis" ay nagpapahayag ng kilos nang walang tinatanggap na layon.','both'),

('General Education','Filipino - Gramatika','easy','Ang unlapi na "mag-" ay nagpapahiwatig ng:','[{"key":"A","text":"Nakaraan"},{"key":"B","text":"Pangkasalukuyan"},{"key":"C","text":"Kakayahan"},{"key":"D","text":"Utos o galaw"}]','D','Ang unlapi na "mag-" ay karaniwang ginagamit upang ipahayag ang galaw o aksyon: maglaro, magluto, magtrabaho.','both'),

('General Education','Filipino - Gramatika','medium','Alin sa mga sumusunod ang may tamang gamit ng gitlapi?','[{"key":"A","text":"Sulatan"},{"key":"B","text":"Sumulat"},{"key":"C","text":"Sinulat"},{"key":"D","text":"Magsulat"}]','C','Ang gitlapi na "-in-" ay nagpapahayag ng naganap na kilos: s-in-ulat = sinulat (nakaraan).','both'),

('General Education','Filipino - Gramatika','easy','Ang "malaking bahay" ay nagtataglay ng pang-uri na:','[{"key":"A","text":"Pang-uri ng dami"},{"key":"B","text":"Pang-uri ng uri"},{"key":"C","text":"Pang-uri ng wastong pangalan"},{"key":"D","text":"Pang-uri ng bilang"}]','B','Ang pang-uri ng uri ay naglalarawan ng katangian o kalidad ng pangngalan: malaki, maliit, maganda.','both'),

('General Education','Filipino - Gramatika','medium','Sa pangungusap na "Ang bata ay matalino," ang "matalino" ay:','[{"key":"A","text":"Paksa"},{"key":"B","text":"Panaguri"},{"key":"C","text":"Layon"},{"key":"D","text":"Panlapi"}]','B','Ang panaguri ay nagbibigay ng impormasyon tungkol sa paksa. Dito, ang "matalino" ay nagsasabi ng katangian ng paksa na "bata."','both'),

('General Education','Filipino - Gramatika','easy','Ang kasingkahulugan ng salitang "makulay" ay:','[{"key":"A","text":"Maputi"},{"key":"B","text":"Maliwanag"},{"key":"C","text":"Masaya"},{"key":"D","text":"Magara"}]','D','"Magara" ay katumbas ng makulay o maliwanag ang hitsura — parehong nagpapahayag ng kagandahan o sigla.','both'),

('General Education','Filipino - Gramatika','medium','Alin ang tamang gamit ng pang-abay na panlunan?','[{"key":"A","text":"Mabilis siyang tumakbo."},{"key":"B","text":"Tumakbo siya kahapon."},{"key":"C","text":"Tumakbo siya sa parke."},{"key":"D","text":"Tumakbo siya nang dalawang beses."}]','C','Ang pang-abay na panlunan ay nagpapahiwatig ng lugar: "sa parke."','both'),

('General Education','Filipino - Panitikan','medium','Si Francisco Balagtas ay kilala bilang may-akda ng:','[{"key":"A","text":"Ibong Adarna"},{"key":"B","text":"Florante at Laura"},{"key":"C","text":"Noli Me Tangere"},{"key":"D","text":"El Filibusterismo"}]','B','Si Francisco Baltazar (Balagtas) ang sumulat ng awit na "Florante at Laura" noong 1838.','both'),

('General Education','Filipino - Panitikan','medium','Ang "Ibong Adarna" ay isang uri ng:','[{"key":"A","text":"Nobela"},{"key":"B","text":"Maikling kwento"},{"key":"C","text":"Korido o awit"},{"key":"D","text":"Dula"}]','C','Ang Ibong Adarna ay isang korido — isang uri ng tulang pampanitikang may mahabang salaysay.','both'),

('General Education','Filipino - Panitikan','easy','Ang "alamat" ay isang uri ng:','[{"key":"A","text":"Tula"},{"key":"B","text":"Katutubong panitikan (folk literature)"},{"key":"C","text":"Nobelang pangkasaysayan"},{"key":"D","text":"Sanaysay"}]','B','Ang alamat ay bahagi ng katutubong panitikan na nagpapaliwanag sa pinagmulan ng mga bagay, lugar, o kaugalian.','both'),

('General Education','Filipino - Panitikan','medium','Ang epiko ng Pilipinas na nagmula sa Mindanao na nagtatampok kay Agyu bilang bayani ay:','[{"key":"A","text":"Biag ni Lam-ang"},{"key":"B","text":"Hinilawod"},{"key":"C","text":"Darangen"},{"key":"D","text":"Alim"}]','C','Ang Darangen ay isang epiko ng Maranao mula Mindanao na nagtatampok sa mga pakikipaglaban ng mga bayaning sina Agyu.','both'),

('General Education','Filipino - Panitikan','easy','Ang bugtong ay isang uri ng:','[{"key":"A","text":"Sanaysay"},{"key":"B","text":"Palaisipan o riddle"},{"key":"C","text":"Korido"},{"key":"D","text":"Tulang Panliriko"}]','B','Ang bugtong ay isang katutubong palaisipan (riddle) na gumagamit ng talinghaga o pahiwatig upang larawan ang sagot.','both'),

('General Education','Filipino - Panitikan','medium','Ang salawikain ay:','[{"key":"A","text":"Isang uri ng maikli at makulay na pahayag na nagtataglay ng karunungan"},{"key":"B","text":"Isang uri ng palaisipan"},{"key":"C","text":"Isang uri ng epiko"},{"key":"D","text":"Isang uri ng dula"}]','A','Ang salawikain (proverb) ay maikling pahayag na nagtataglay ng katotohanan o karunungang pangkultura.','both'),

('General Education','Filipino - Panitikan','medium','Alin sa mga sumusunod ang isang halimbawa ng metapora sa Filipino?','[{"key":"A","text":"Ang buhay ay parang isang laro."},{"key":"B","text":"Ang guro ay ilaw ng bayan."},{"key":"C","text":"Ang bata ay tumakbo tulad ng hangin."},{"key":"D","text":"Ang bulaklak ay humihinga nang dahan-dahan."}]','B','Ang metapora ay direktang paghambing nang walang "parang" o "tulad ng": "Ang guro ay ilaw ng bayan."','both'),

('General Education','Filipino - Kasaysayan ng Wika','medium','Ang Filipino bilang opisyal na wika ng Pilipinas ay nagsimula noong:','[{"key":"A","text":"1898"},{"key":"B","text":"1937"},{"key":"C","text":"1946"},{"key":"D","text":"1987"}]','B','Sa pamamagitan ng Komisyonado ng Edukasyon noong 1937, pinili ang Tagalog bilang batayan ng pambansang wika.','both'),

('General Education','Filipino - Kasaysayan ng Wika','medium','Ang Komisyon sa Wikang Filipino (KWF) ay responsable sa:','[{"key":"A","text":"Pagtuturo ng Ingles"},{"key":"B","text":"Pagpapaunlad at pagpapalawak ng wikang Filipino"},{"key":"C","text":"Pagsusulat ng mga batas"},{"key":"D","text":"Pamamahala ng mga paaralan"}]','B','Ang KWF ang opisyal na katawan ng pamahalaan na nagpapalago, nagtataguyod, at nagpapanatili ng wikang Filipino.','both'),

('General Education','Filipino - Gramatika','hard','Alin ang tamang paggamit ng "ng" at "nang"?','[{"key":"A","text":"Pumunta siya ng mabilis."},{"key":"B","text":"Pumunta siya nang mabilis."},{"key":"C","text":"Nang pumunta siya ng tindahan."},{"key":"D","text":"Ang tindahan ay nang malayo."}]','B','"Nang" ay ginagamit bilang pang-abay (adverb) na nagpapaliwanag sa pandiwa: "nang mabilis." Ang "ng" ay ginagamit bilang pantukoy ng layon.','both'),

('General Education','Filipino - Panitikan','easy','Ang "Noli Me Tangere" sa Filipino ay nangangahulugang:','[{"key":"A","text":"Huwag Akong Galawin"},{"key":"B","text":"Mahal Kita, Pilipinas"},{"key":"C","text":"Ako ay Pilipino"},{"key":"D","text":"Lupain ng Aking mga Ama"}]','A','"Noli Me Tangere" ay Latin para sa "Huwag Akong Galawin" — nagpapahiwatig ng sakit ng bayan.','both'),

('General Education','Filipino - Gramatika','medium','Ang "mahal" sa pangungusap na "Mahal ko ang aking bayan" ay:','[{"key":"A","text":"Pang-abay"},{"key":"B","text":"Pandiwa"},{"key":"C","text":"Pang-uri na ginamit bilang pandiwa"},{"key":"D","text":"Pangngalan"}]','C','Ang "mahal" dito ay ginagamit bilang pandiwang nagpapahayag ng damdamin (love/value) — pang-uring nagsilbing pandiwa.','both'),

('General Education','Filipino - Panitikan','medium','Ang awiting bayan o kundiman ay isang uri ng:','[{"key":"A","text":"Folk song na nagpapahayag ng pagmamahal sa bayan at romantikong damdamin"},{"key":"B","text":"Dula pangkomunidad"},{"key":"C","text":"Epikong pampanitikan"},{"key":"D","text":"Maikling kwento"}]','A','Ang kundiman ay isang tradisyonal na Pilipinong awitin na nagpapahayag ng pagmamahal, kalungkutan, at pagpapahalaga sa bayan.','both'),

('General Education','Filipino - Gramatika','easy','Ang kasalungat ng salitang "masama" ay:','[{"key":"A","text":"Maganda"},{"key":"B","text":"Mabuti"},{"key":"C","text":"Malungkot"},{"key":"D","text":"Maingay"}]','B','Ang kasalungat (antonym) ng "masama" ay "mabuti" — ang isa ay negatibo at ang isa ay positibo.','both'),

('General Education','Filipino - Panitikan','hard','Alin sa mga sumusunod ang bahagi ng "Florante at Laura" na nagpapakita ng pagmamahal ni Balagtas sa sariling bayan?','[{"key":"A","text":"Ang pakikipaglaban ni Florante kay Adolfo"},{"key":"B","text":"Ang pagmamahal ni Florante kay Laura"},{"key":"C","text":"Ang mga pangyayari sa Albania bilang salamin ng Pilipinas sa ilalim ng pananakop"},{"key":"D","text":"Ang pagbabalik ni Florante sa kanyang tahanan"}]','C','Ginamit ni Balagtas ang Albania bilang alegorya para sa Pilipinas sa ilalim ng kolonyalismong Espanyol, at si Florante bilang simbolo ng api.','both'),

('General Education','Filipino - Kasaysayan ng Wika','medium','Ang wikang Filipino ay nakabatay sa:','[{"key":"A","text":"Ingles"},{"key":"B","text":"Tagalog"},{"key":"C","text":"Español"},{"key":"D","text":"Ilocano"}]','B','Ayon sa Konstitusyon ng 1987, ang Filipino ay ang pambansang wika na nakabatay sa Tagalog.','both'),

('General Education','Filipino - Gramatika','medium','Ang hulapi na "-an" sa salitang "tirahan" ay nagpapahiwatig ng:','[{"key":"A","text":"Kilos"},{"key":"B","text":"Lugar"},{"key":"C","text":"Katangian"},{"key":"D","text":"Tagaganap"}]','B','Ang hulapi na "-an" ay kadalasang nagbibigay ng kahulugang lugar: tirahan (lugar ng tirahan), lutuan (lugar ng pagluluto).','both'),

-- ADDITIONAL PROFESSIONAL EDUCATION (451-500)
('Professional Education','Educational Technology','medium','ICT integration in the classroom aims to:','[{"key":"A","text":"Replace teachers completely"},{"key":"B","text":"Enhance teaching and learning through technology tools"},{"key":"C","text":"Reduce school expenses"},{"key":"D","text":"Entertain students during free time"}]','B','ICT integration uses technology as a tool to enhance instruction, engagement, and learning outcomes — not to replace teachers.','both'),

('Professional Education','Educational Technology','medium','The SAMR model (Substitution, Augmentation, Modification, Redefinition) describes:','[{"key":"A","text":"Student behavior management levels"},{"key":"B","text":"Levels of technology integration in education"},{"key":"C","text":"Assessment rubric levels"},{"key":"D","text":"Curriculum development stages"}]','B','SAMR describes how technology transforms learning: from substitution (same task, tech tool) to redefinition (tasks impossible without tech).','both'),

('Professional Education','Educational Technology','easy','A Learning Management System (LMS) is used to:','[{"key":"A","text":"Manage school finances"},{"key":"B","text":"Deliver, track, and manage online learning content"},{"key":"C","text":"Conduct face-to-face examinations"},{"key":"D","text":"Replace the school library"}]','B','An LMS (like Google Classroom, Moodle) is a platform for creating, delivering, and tracking online courses and learning activities.','both'),

('Professional Education','Facilitating Learning','hard','The concept of "scaffolded instruction" in a classroom means the teacher:','[{"key":"A","text":"Builds physical structures for science lessons"},{"key":"B","text":"Provides decreasing levels of support as student competence grows"},{"key":"C","text":"Uses only physical manipulatives"},{"key":"D","text":"Avoids helping students to promote independence"}]','B','Scaffolded instruction provides temporary support (hints, models, prompts) that is gradually removed as the learner becomes more capable.','both'),

('Professional Education','Assessment of Learning','hard','Washback effect in assessment refers to:','[{"key":"A","text":"Water-based science experiments"},{"key":"B","text":"The influence of testing on teaching and learning practices"},{"key":"C","text":"Retaking of failed examinations"},{"key":"D","text":"Feedback given to students after tests"}]','B','Washback (backwash) is the effect that tests have on teaching — teachers may "teach to the test" if high-stakes assessments drive curriculum.','both'),

('Professional Education','Principles of Teaching','hard','Socratic questioning is characterized by:','[{"key":"A","text":"Teacher lecturing while students take notes"},{"key":"B","text":"Teacher asking probing questions to develop critical thinking"},{"key":"C","text":"Students answering only yes or no"},{"key":"D","text":"Peer teaching strategies"}]','B','Socratic method uses systematic questioning to help students examine assumptions, uncover contradictions, and develop deeper understanding.','both'),

('Professional Education','Child and Adolescent Development','hard','Resilience in child development refers to:','[{"key":"A","text":"Physical strength and endurance"},{"key":"B","text":"The capacity to recover and adapt positively in the face of adversity"},{"key":"C","text":"Academic excellence under pressure"},{"key":"D","text":"Emotional sensitivity"}]','B','Resilience is the ability to bounce back from challenges, trauma, or adverse conditions — a key protective factor in child development.','both'),

('Professional Education','Curriculum Development','hard','The "hidden curriculum" most commonly transmits:','[{"key":"A","text":"Official academic content"},{"key":"B","text":"Social values, norms, and expectations"},{"key":"C","text":"Test-taking strategies"},{"key":"D","text":"Physical education skills"}]','B','The hidden curriculum operates through school culture, teacher behavior, and classroom norms — transmitting values, social rules, and expectations.','both'),

('Professional Education','Principles of Teaching','medium','Inquiry-based learning best develops which 21st century skill?','[{"key":"A","text":"Rote memorization"},{"key":"B","text":"Critical thinking and problem solving"},{"key":"C","text":"Penmanship"},{"key":"D","text":"Speed reading"}]','B','Inquiry-based learning, where students investigate questions and discover answers, directly develops critical thinking and problem-solving skills.','both'),

('Professional Education','Assessment of Learning','medium','A quiz given at the start of a lesson to check what students know is called:','[{"key":"A","text":"Summative assessment"},{"key":"B","text":"Formative assessment"},{"key":"C","text":"Diagnostic assessment"},{"key":"D","text":"Benchmarking"}]','C','A pre-lesson quiz is diagnostic — it determines what students already know before instruction begins.','both'),

('Professional Education','Facilitating Learning','medium','The concept of "prior knowledge" in learning is important because:','[{"key":"A","text":"It determines intelligence"},{"key":"B","text":"New learning is built upon and connected to what is already known"},{"key":"C","text":"It allows students to skip lessons"},{"key":"D","text":"It measures exam readiness"}]','B','Research consistently shows that activating and connecting to prior knowledge is critical for meaningful learning and retention.','both'),

('Professional Education','Principles of Teaching','medium','Demonstration as a teaching method is most effective when:','[{"key":"A","text":"Students only observe without any participation"},{"key":"B","text":"The teacher performs the skill step by step, then students practice"},{"key":"C","text":"Abstract concepts are being introduced"},{"key":"D","text":"Students are being tested"}]','B','Demonstration is most effective when followed by guided and independent practice — allowing students to replicate the demonstrated skill.','both'),

('Professional Education','Child and Adolescent Development','medium','According to Vygotsky, learning is fundamentally:','[{"key":"A","text":"An individual, solitary process"},{"key":"B","text":"A social process mediated by interaction"},{"key":"C","text":"Purely based on biological maturation"},{"key":"D","text":"Driven by behavioral conditioning"}]','B','Vygotsky''s core thesis is that higher mental functions develop through social interaction and are then internalized by the individual.','both'),

('Professional Education','Curriculum Development','medium','Which curriculum model starts from the learner''s needs and interests?','[{"key":"A","text":"Subject-centered design"},{"key":"B","text":"Learner-centered design"},{"key":"C","text":"Problem-centered design"},{"key":"D","text":"Core curriculum design"}]','B','Learner-centered curriculum design places students'' interests, needs, and experiences at the center of curriculum planning.','both'),

('Professional Education','Assessment of Learning','medium','The purpose of giving detailed written feedback on student work is to:','[{"key":"A","text":"Show the teacher''s authority"},{"key":"B","text":"Guide student improvement and learning"},{"key":"C","text":"Document student failure"},{"key":"D","text":"Reduce the need for oral discussion"}]','B','Detailed feedback informs students of strengths and areas for improvement, driving learning forward.','both'),

('Professional Education','Facilitating Learning','medium','Experiential learning (Kolb) involves which cycle?','[{"key":"A","text":"Lecture → Test → Grade → Repeat"},{"key":"B","text":"Concrete Experience → Reflective Observation → Abstract Conceptualization → Active Experimentation"},{"key":"C","text":"Read → Recite → Review → Test"},{"key":"D","text":"Observe → Memorize → Apply → Forget"}]','B','Kolb''s experiential learning cycle: doing (concrete experience) → reflecting → thinking (abstract concepts) → experimenting.','both'),

('Professional Education','The Teaching Profession','hard','The principle of "academic freedom" for teachers means:','[{"key":"A","text":"Teachers can teach anything without accountability"},{"key":"B","text":"Teachers have the right to teach their subject using their professional judgment"},{"key":"C","text":"Students can choose not to attend class"},{"key":"D","text":"Schools cannot evaluate teacher performance"}]','B','Academic freedom gives teachers professional autonomy in selecting methods, materials, and approaches within ethical and curricular boundaries.','both'),

('Professional Education','Principles of Teaching','medium','The 4A''s lesson plan format stands for:','[{"key":"A","text":"Assess, Aim, Apply, Achieve"},{"key":"B","text":"Activity, Analysis, Abstraction, Application"},{"key":"C","text":"Attention, Acquire, Assess, Apply"},{"key":"D","text":"Ask, Answer, Analyze, Act"}]','B','The 4A''s (Activity, Analysis, Abstraction, Application) is a common Philippine lesson plan format promoting active, constructivist learning.','both'),

('Professional Education','Assessment of Learning','medium','The difference between assessment OF learning and assessment FOR learning is:','[{"key":"A","text":"They are the same thing with different names"},{"key":"B","text":"Assessment OF learning evaluates achievement; assessment FOR learning guides ongoing instruction"},{"key":"C","text":"Assessment FOR learning is only used in college"},{"key":"D","text":"Assessment OF learning is informal"}]','B','Assessment OF learning is summative (grades, certification); assessment FOR learning is formative (feedback to improve ongoing learning).','both'),

('Professional Education','Child and Adolescent Development','medium','Special education (SPED) in the Philippines provides services for:','[{"key":"A","text":"Gifted students only"},{"key":"B","text":"Students with various disabilities and special learning needs"},{"key":"C","text":"Students who failed regular classes"},{"key":"D","text":"International students"}]','B','SPED provides individualized education programs for learners with physical, intellectual, learning, or behavioral disabilities.','both'),

('Professional Education','Facilitating Learning','hard','The "testing effect" in cognitive science shows that:','[{"key":"A","text":"Tests cause anxiety and reduce learning"},{"key":"B","text":"Retrieving information through testing improves long-term retention"},{"key":"C","text":"Multiple choice tests are the most effective"},{"key":"D","text":"Frequent testing reduces motivation"}]','B','The testing effect (retrieval practice) demonstrates that actively recalling information strengthens memory more than re-reading.','both'),

('Professional Education','Principles of Teaching','medium','Collaborative learning differs from competitive learning because it:','[{"key":"A","text":"Requires students to work alone"},{"key":"B","text":"Encourages mutual support and shared goals"},{"key":"C","text":"Ranks students against each other"},{"key":"D","text":"Eliminates individual accountability"}]','B','Collaborative learning structures students to work together toward shared goals, building communication and teamwork skills.','both'),

('Professional Education','Curriculum Development','medium','DepEd''s Mother Tongue-Based Multilingual Education (MTB-MLE) policy requires:','[{"key":"A","text":"English to be the sole medium of instruction from Grade 1"},{"key":"B","text":"Teaching using the child''s first language (mother tongue) in Grades 1–3"},{"key":"C","text":"All subjects to be taught in Filipino only"},{"key":"D","text":"Students to learn three languages simultaneously from birth"}]','B','MTB-MLE uses the learner''s mother tongue as the primary medium of instruction in Grades 1–3 to build stronger literacy foundations.','both'),

('Professional Education','Assessment of Learning','medium','An exit ticket at the end of class is an example of:','[{"key":"A","text":"Summative assessment"},{"key":"B","text":"Formative assessment"},{"key":"C","text":"Diagnostic assessment"},{"key":"D","text":"Portfolio assessment"}]','B','Exit tickets (brief end-of-class checks) are formative — they provide quick feedback on student understanding to guide future lessons.','both'),

('Professional Education','Principles of Teaching','hard','The concept of "differentiated instruction" is most aligned with which of these principles?','[{"key":"A","text":"All students learn in the same way and pace"},{"key":"B","text":"Students have varied readiness, interests, and learning profiles that should guide instruction"},{"key":"C","text":"Teachers should use only one teaching method per class"},{"key":"D","text":"Assessment should be identical for all students"}]','B','Differentiated instruction acknowledges learning differences and responds by varying content, process, and product to meet diverse student needs.','both'),

('Professional Education','Child and Adolescent Development','medium','Lev Vygotsky''s concept of "more knowledgeable other" (MKO) refers to:','[{"key":"A","text":"The school principal"},{"key":"B","text":"Anyone with greater knowledge who can guide the learner"},{"key":"C","text":"A student''s parent only"},{"key":"D","text":"A licensed teacher only"}]','B','The MKO can be a teacher, peer, parent, or anyone who has more knowledge or skill relevant to a task, helping the learner through the ZPD.','both'),

('Professional Education','Facilitating Learning','medium','According to Bloom, the highest level of the affective domain is:','[{"key":"A","text":"Receiving"},{"key":"B","text":"Responding"},{"key":"C","text":"Valuing"},{"key":"D","text":"Characterization by a value complex"}]','D','The affective domain (Krathwohl) has 5 levels: Receiving → Responding → Valuing → Organization → Characterization (highest).','both'),

('Professional Education','Principles of Teaching','medium','The role of the teacher as a "facilitator of learning" means:','[{"key":"A","text":"The teacher is the sole source of knowledge"},{"key":"B","text":"The teacher guides, supports, and creates conditions for students to construct meaning"},{"key":"C","text":"The teacher only observes without intervening"},{"key":"D","text":"The teacher replaces all direct instruction with student activities"}]','B','As facilitator, the teacher shifts from information transmitter to guide who creates learning environments where students actively construct knowledge.','both'),

('Professional Education','Assessment of Learning','hard','Triangulation in assessment means:','[{"key":"A","text":"Using three-sided rubrics"},{"key":"B","text":"Using multiple sources of evidence to assess learning"},{"key":"C","text":"Giving three tests per quarter"},{"key":"D","text":"Group assessment of three students"}]','B','Triangulation uses multiple assessment methods (tests, observations, projects) to build a more valid, comprehensive picture of student learning.','both'),

('Professional Education','The Teaching Profession','medium','A teacher who demonstrates "culturally responsive teaching" does what?','[{"key":"A","text":"Teaches only the official curriculum without cultural additions"},{"key":"B","text":"Acknowledges and incorporates students'' cultural backgrounds into instruction"},{"key":"C","text":"Avoids discussing culture in the classroom"},{"key":"D","text":"Teaches only in the national language"}]','B','Culturally responsive teaching uses students'' cultural backgrounds, experiences, and perspectives as resources to make learning relevant and equitable.','both'),

('Professional Education','Facilitating Learning','medium','The VARK learning model categorizes learners as:','[{"key":"A","text":"Visual, Auditory, Reading/Writing, Kinesthetic"},{"key":"B","text":"Verbal, Auditory, Rational, Kinetic"},{"key":"C","text":"Visual, Abstract, Realistic, Kinesthetic"},{"key":"D","text":"Verbal, Analytical, Responsive, Kinesthetic"}]','A','VARK (Fleming) identifies four learning preferences: Visual, Auditory, Reading/Writing, and Kinesthetic.','both'),

('Professional Education','Principles of Teaching','medium','The technique of "think alouds" involves:','[{"key":"A","text":"Students thinking silently during tests"},{"key":"B","text":"The teacher verbalizing their thought process while solving a problem"},{"key":"C","text":"Class debates on controversial topics"},{"key":"D","text":"Reading comprehension exercises"}]','B','Think-alouds make invisible cognitive processes visible by having the teacher verbalize their reasoning, modeling metacognitive strategies.','both'),

('Professional Education','Assessment of Learning','medium','Grading on a curve adjusts scores based on:','[{"key":"A","text":"Individual student improvement"},{"key":"B","text":"The class average or highest score"},{"key":"C","text":"National standards"},{"key":"D","text":"The teacher''s subjective judgment"}]','B','Curving adjusts grades relative to overall class performance — typically raising scores when the test was too difficult.','both'),

('Professional Education','Child and Adolescent Development','medium','Gender and development (GAD) in education promotes:','[{"key":"A","text":"Teaching boys and girls separately"},{"key":"B","text":"Equal opportunities and elimination of gender stereotypes in schools"},{"key":"C","text":"Prioritizing male students in STEM"},{"key":"D","text":"Teaching only gender-related subjects"}]','B','GAD in education addresses gender-based inequalities and stereotypes, promoting inclusive and equitable learning for all.','both'),

('Professional Education','Facilitating Learning','medium','The concept of "learned helplessness" (Seligman) in education describes:','[{"key":"A","text":"Students who study too much"},{"key":"B","text":"Students who stop trying after repeated failures, believing effort is futile"},{"key":"C","text":"Students who depend on technology"},{"key":"D","text":"Teachers who give too much help"}]','B','Learned helplessness occurs when students, after repeated uncontrollable failures, believe their actions have no effect on outcomes and stop trying.','both'),

('Professional Education','Principles of Teaching','easy','Which teaching strategy is best for developing students'' presentation and public speaking skills?','[{"key":"A","text":"Silent seatwork"},{"key":"B","text":"Multiple choice tests"},{"key":"C","text":"Oral reports and demonstrations"},{"key":"D","text":"Flash card drills"}]','C','Oral reports and demonstrations give students structured opportunities to practice and develop presentation and communication skills.','both');
